package com.dreams.vehicle.greenhouse_metrics.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Random;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "vehicle_emissions")
public class VehicleEmission {

    @Id
    private String id;
    private String vehicleType;
    private double carbonEmission;

    public static VehicleEmission generateRandomEmission() {
        String[] vehicleTypes = {"Car", "Truck", "Bus", "SUV", "Motorcycle"};
        Random random = new Random();
        String type = vehicleTypes[random.nextInt(vehicleTypes.length)];
        double emission = random.nextDouble() * 100; // Random emission value
        return new VehicleEmission(null, type, emission); // ID is generated by MongoDB
    }
}

